name: fileshare

services:
  database:
    image: postgres:alpine
    restart: no
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  cache:
    image: redis:alpine
    restart: no
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "5540:5540"

  backend:
    restart: on-failure:3
    depends_on:
      - database
      - cache
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
      - POSTGRES_SERVER=database
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not sat}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - REDIS_SERVER=cache
      - REDIS_PASSWORD=${REDIS_PASSWORD?Variable not set}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    build:
      context: ./backend
    ports:
      - "8000:80"

volumes:
  app-db-data:
  cache:
    driver: local
